import { precacheAndRoute } from 'workbox-precaching';

// Precaching all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Listen for push events
self.addEventListener('push', function(event) {
  if (event.data) {
    try {
      const data = event.data.json();
      const options = {
        body: data.body || 'You have a new message',
        icon: '/pepi-logo.png',
        badge: '/pepi-logo.png',
        data: data.url || '/',
        vibrate: [100, 50, 100],
      };
      
      event.waitUntil(
        self.registration.showNotification(data.title || 'Centaur Deploy', options)
      );
    } catch (e) {
      console.error('[SW] Push event error parsing JSON', e);
      // Fallback
      event.waitUntil(
        self.registration.showNotification('Centaur Deploy', {
          body: event.data.text(),
          icon: '/pepi-logo.png',
        })
      );
    }
  }
});

// Handle notification click
self.addEventListener('notificationclick', function(event) {
  event.notification.close();
  const urlToOpen = event.notification.data || '/';
  
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window/tab open with the target URL
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        // If so, just focus it.
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, then open the target URL in a new window/tab.
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});
